version: "3"
services:
  imag-oee:
    image: vanvuong24072001/imag-oee:1.1
    volumes:
      - ./src/main/resources/DataExcel:/usr/local/bin/app/src/main/resources/DataExcel
    ports:
      - "8080:8081"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=oee-db